if(Drupal.jsEnabled){$(document).ready(function(){if($("#edit-pathauto-perform-alias").size()&&$("#edit-pathauto-perform-alias").attr("checked")){$("#edit-path").attr("disabled","disabled");$("#edit-path-wrapper > div.description").hide(0)};$("#edit-pathauto-perform-alias").bind("click",function(){if($("#edit-pathauto-perform-alias").attr("checked")){$("#edit-path").attr("disabled","disabled");$("#edit-path-wrapper > div[class=description]").slideUp('fast')}else{$("#edit-path").removeAttr("disabled");$("#edit-path")[0].focus();$("#edit-path-wrapper > div[class=description]").slideDown('fast')}})});Drupal.verticalTabs=Drupal.verticalTabs||{};Drupal.verticalTabs.path=function(){var path=$('#edit-path').val(),automatic=$('#edit-pathauto-perform-alias').attr('checked');if(automatic)return Drupal.t('Automatic alias');if(path){return Drupal.t('Alias: @alias',{'@alias':path})}else return Drupal.t('No alias')}};
Drupal.verticalTabs=Drupal.verticalTabs||{};Drupal.verticalTabs.revision_information=function(){if($('#edit-revision').length){if($('#edit-revision').attr('checked')){return Drupal.t('New revision')}else return Drupal.t('No revision')}else return''};Drupal.verticalTabs.author=function(){var author=$('#edit-name').val()||Drupal.t('Anonymous'),date=$('#edit-date').val();if(date){return Drupal.t('By @name on @date',{'@name':author,'@date':date})}else return Drupal.t('By @name',{'@name':author})};Drupal.verticalTabs.options=function(){var vals=[];$('fieldset.vertical-tabs-options input:checked').parent().each(function(){vals.push(Drupal.checkPlain($.trim($(this).text())))});if(!$('#edit-status').is(':checked'))vals.unshift(Drupal.t('Not published'));return vals.join(', ')};

Drupal.verticalTabs = Drupal.verticalTabs || {};

Drupal.verticalTabs.comment_settings = function() {
  return $('.vertical-tabs-comment_settings input:checked').parent().text();
}

Drupal.verticalTabs.comment = function() {
  var vals = [];
  vals.push($(".vertical-tabs-comment input[name='comment']:checked").parent().text());
  vals.push($(".vertical-tabs-comment input[name='comment_default_mode']:checked").parent().text());
  vals.push(Drupal.t('@number comments per page', {'@number': $(".vertical-tabs-comment select[name='comment_default_per_page'] option:selected").val()}));
  return vals.join(', ');
}
;
Drupal.verticalTabs=Drupal.verticalTabs||{};Drupal.verticalTabs.menu=function(){if($('#edit-menu-link-title').val()){return Drupal.checkPlain($('#edit-menu-link-title').val())}else return Drupal.t('Not in menu')};
Drupal.behaviors.teaser=function(context){if(/KDE/.test(navigator.vendor))return;$('textarea.teaser:not(.teaser-processed)',context).each(function(){var teaser=$(this).addClass('teaser-processed'),body=$('#'+Drupal.settings.teaser[this.id]),checkbox=$('#'+Drupal.settings.teaserCheckbox[this.id]).parent(),checked=$(checkbox).children('input').attr('checked')?true:false,parent=teaser[0].parentNode;$(body).before(teaser);$(parent).remove()
function trim(text){return text.replace(/^\s+/g,'').replace(/\s+$/g,'')}
function join_teaser(){if(teaser.val())body.val(trim(teaser.val())+'\r\n\r\n'+trim(body.val()));teaser[0].value='';$(teaser).attr('disabled','disabled');$(teaser).parent().slideUp('fast');$(this).val(Drupal.t('Split summary at cursor'));$(checkbox).hide();checked=$(checkbox).children('input').attr('checked')?true:false;$(checkbox).children('input').attr('checked',true)}
function split_teaser(){body[0].focus();var selection=Drupal.getSelection(body[0]),split=selection.start,text=body.val();teaser[0].value=trim(text.slice(0,split));body[0].value=trim(text.slice(split));$(teaser).attr('disabled','');$(teaser).parent().slideDown('fast');$(this).val(Drupal.t('Join summary'));$(checkbox).show().children('input').attr('checked',checked)};var button=$('<div class="teaser-button-wrapper"><input type="button" class="teaser-button" /></div>'),include=$('#'+this.id.substring(0,this.id.length-2)+'include');$(include).parent().parent().before(button);var text=body.val().split('<!--break-->');if(text.length>=2){teaser[0].value=trim(text.shift());body[0].value=trim(text.join('<!--break-->'));$(teaser).attr('disabled','');$('input',button).val(Drupal.t('Join summary')).toggle(join_teaser,split_teaser)}else{$('input',button).val(Drupal.t('Split summary at cursor')).toggle(split_teaser,join_teaser);$(checkbox).hide().children('input').attr('checked',true)};if(Drupal.behaviors.textarea&&teaser.is('.form-textarea:not(.textarea-processed)'))Drupal.behaviors.textarea(teaser.parentNode);if($(teaser).is(':disabled'))$(teaser).parent().hide()})};
